// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxAHW0_Ep0ne29qpOjSovbuOOu_uja4BA',
    appId: '1:380505063144:android:bc24a6421b4f200ac4135d',
    messagingSenderId: '380505063144',
    projectId: 'keep-me-hydrated',
    storageBucket: 'keep-me-hydrated.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB36sbsfuvXgEbXzN0w0hDYLvfZnZWt2tY',
    appId: '1:380505063144:ios:388b6b3fb7f73404c4135d',
    messagingSenderId: '380505063144',
    projectId: 'keep-me-hydrated',
    storageBucket: 'keep-me-hydrated.firebasestorage.app',
    androidClientId: '380505063144-0hojdamjlrmf8itam8c8cgb7ur7vhhff.apps.googleusercontent.com',
    iosClientId: '380505063144-edu2o4t2dp59ro14kscb6dvp0a18jbfd.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantProject',
  );

}